# Generated by Django 5.2.11 on 2026-02-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='phone_number',
            field=models.CharField(default='Not provided', max_length=20),
            preserve_default=False,
        ),
    ]
